import { NextResponse } from "next/server";
import { deleteCompanyDocument, getCompanyDocument, getCompanyDocumentText, ingestCompanyDocument, reparseCompanyDocument, workspaceStats } from "@/lib/tender-agent/company-workspace";
import type { CompanyDocumentCategory } from "@/types/tender-agent";

export const runtime = "nodejs";
const categories = new Set<CompanyDocumentCategory>(["company", "qualification", "personnel", "case", "product", "capability", "delivery", "after-sales", "other"]);
export async function GET(request: Request) { const url = new URL(request.url); const documentId = url.searchParams.get("documentId"); if (documentId) { const document = await getCompanyDocument(documentId); if (!document) return NextResponse.json({ message: "资料不存在。" }, { status: 404 }); return NextResponse.json({ document, text: url.searchParams.get("includeText") === "1" ? await getCompanyDocumentText(documentId) : undefined }); } return NextResponse.json({ documents: await (await import("@/lib/tender-agent/company-workspace")).listCompanyDocuments(), stats: await workspaceStats() }); }
export async function POST(request: Request) { try { const data = await request.formData(); const file = data.get("file"); const category = String(data.get("category") || "other") as CompanyDocumentCategory; if (!(file instanceof File) || !categories.has(category)) return NextResponse.json({ message: "请提供资料文件和有效分类。" }, { status: 400 }); const tags = String(data.get("tags") || "").split(/[，,]/).map((item) => item.trim()).filter(Boolean); const document = await ingestCompanyDocument(file, category, { validFrom: String(data.get("validFrom") || "") || undefined, validTo: String(data.get("validTo") || "") || undefined, issuer: String(data.get("issuer") || "") || undefined, tags }); return NextResponse.json({ document, stats: await workspaceStats() }); } catch (error) { return NextResponse.json({ message: error instanceof Error ? error.message : "资料导入失败。" }, { status: 422 }); } }
export async function PUT(request: Request) { try { const { documentId } = await request.json() as { documentId?: string }; if (!documentId) return NextResponse.json({ message: "缺少 documentId。" }, { status: 400 }); return NextResponse.json({ document: await reparseCompanyDocument(documentId), stats: await workspaceStats() }); } catch (error) { return NextResponse.json({ message: error instanceof Error ? error.message : "重新解析失败。" }, { status: 422 }); } }
export async function DELETE(request: Request) { const { documentId } = await request.json() as { documentId?: string }; if (!documentId) return NextResponse.json({ message: "缺少 documentId。" }, { status: 400 }); await deleteCompanyDocument(documentId); return NextResponse.json({ stats: await workspaceStats() }); }
