export const siteConfig = {
  links: {
    github: "https://github.com/neyoxxx16-maker",
    email: "mailto:1651870652@qq.com?subject=AI%E5%94%AE%E5%89%8D%E5%B2%97%E4%BD%8D%E6%B2%9F%E9%80%9A%EF%BD%9C%E9%BB%84%E5%BF%B5%E7%BA%A2",
    resumePdf: "/documents/huang-nihong-resume.pdf",
  },
  materials: {
    teaManual: {
      title: "一叶春山｜产品手册",
      description: "茶品牌产品资料与业务方案展示",
      href: "/solutions/yiyeshanchun-product-manual",
      pages: [
        "/manuals/yiyeshanchun/yiyeshanchun-page-01.webp",
        "/manuals/yiyeshanchun/yiyeshanchun-page-02.webp",
        "/manuals/yiyeshanchun/yiyeshanchun-page-03.webp",
        "/manuals/yiyeshanchun/yiyeshanchun-page-04.webp",
        "/manuals/yiyeshanchun/yiyeshanchun-page-05.webp",
        "/manuals/yiyeshanchun/yiyeshanchun-page-06.webp",
        "/manuals/yiyeshanchun/yiyeshanchun-page-07.webp",
        "/manuals/yiyeshanchun/yiyeshanchun-page-08.webp",
        "/manuals/yiyeshanchun/yiyeshanchun-page-09.webp",
        "/manuals/yiyeshanchun/yiyeshanchun-page-10.webp",
      ],
    },
    huawentongManual: {
      title: "华文通｜产品手册",
      description: "产品与解决方案材料展示",
      href: "/solutions/huawentong-product-manual",
      file: "/documents/huawentong-solution-material.pdf",
      pages: [
        "/manuals/huawentong/huawentong-page-01.png",
        "/manuals/huawentong/huawentong-page-02.png",
        "/manuals/huawentong/huawentong-page-03.png",
        "/manuals/huawentong/huawentong-page-04.png",
        "/manuals/huawentong/huawentong-page-05.png",
        "/manuals/huawentong/huawentong-page-06.png",
        "/manuals/huawentong/huawentong-page-07.png",
        "/manuals/huawentong/huawentong-page-08.png",
        "/manuals/huawentong/huawentong-page-09.png",
        "/manuals/huawentong/huawentong-page-10.png",
        "/manuals/huawentong/huawentong-page-11.png",
        "/manuals/huawentong/huawentong-page-12.png",
        "/manuals/huawentong/huawentong-page-13.png",
      ],
    },
  },
} as const;
