import type { ContentAngle, ContentPackage, ContentPlatform, EcommerceAgentRequest, EcommerceProductFacts, StylePreset, VideoScene } from "@/types/ecommerce-agent";

const styleRules: Record<StylePreset, { tone: string; hook: string; structure: string; pacing: string; visual: string; subtitle: string; cta: string; avoid: string[] }> = {
  conversion: { tone: "直接、明确", hook: "痛点与利益点前置", structure: "痛点→方案→事实→行动", pacing: "快", visual: "快切产品细节与大字幕", subtitle: "短促利益点", cta: "明确行动", avoid: ["夸大承诺"] },
  humor: { tone: "口语化、轻松", hook: "反差与生活吐槽", structure: "包袱→反应→产品→收束", pacing: "中快", visual: "反应镜头与停顿", subtitle: "包袱式短字幕", cta: "轻互动", avoid: ["编造事实", "冒犯性玩笑"] },
  education: { tone: "清晰、克制", hook: "知识缺口或误区", structure: "结论→原因→示例→建议", pacing: "稳定", visual: "知识卡与产品示范", subtitle: "结论先行", cta: "收藏学习", avoid: ["伪科学", "功效宣称"] },
  xiaohongshu: { tone: "朋友式分享", hook: "具体生活场景", structure: "场景→体验→细节→互动", pacing: "自然", visual: "桌面、开箱与细节", subtitle: "像手写笔记般简短", cta: "收藏或留言", avoid: ["硬广腔"] },
  story: { tone: "有画面感、克制", hook: "人物和情绪", structure: "场景→情绪→转折→产品", pacing: "偏慢", visual: "自然光与连续叙事", subtitle: "短句留白", cta: "温和收束", avoid: ["强促销"] },
  premium: { tone: "简洁、有分寸", hook: "产品细节与留白", structure: "细节→感受→事实→留白", pacing: "低频", visual: "自然光、产品特写、干净背景", subtitle: "低密度克制排版", cta: "极弱", avoid: ["绝绝子", "闭眼入", "YYDS", "天花板", "过多感叹号"] },
  custom: { tone: "按用户风格要求调整", hook: "按自定义表达特征", structure: "根据用户偏好组织", pacing: "按自定义要求", visual: "与用户风格一致", subtitle: "与用户风格一致", cta: "按用户风格", avoid: [] },
};
const platformLabel: Record<ContentPlatform, string> = { xiaohongshu: "小红书", douyin: "抖音 / 短视频", channels: "视频号", feed: "信息流广告", general: "通用" };
const goalLabel = { seeding: "产品种草", launch: "新品介绍", education: "卖点教育", brand: "品牌传播", conversion: "转化销售", knowledge: "知识科普" } as const;
const presetFrom = (request: EcommerceAgentRequest): StylePreset => request.style === "信息流 / 强转化" ? "conversion" : request.style === "搞笑幽默" ? "humor" : request.style === "科普干货" ? "education" : request.style === "小红书种草" ? "xiaohongshu" : request.style === "故事 / 情绪共鸣" ? "story" : request.style === "品牌高级感" ? "premium" : request.style === "自定义风格" ? "custom" : "xiaohongshu";
const clip = (text: string, limit: number) => text.length > limit ? `${text.slice(0, limit)}…` : text;

function makeAngles(facts: EcommerceProductFacts, request: EcommerceAgentRequest): ContentAngle[] {
  const points = request.sellingPoints?.length ? request.sellingPoints : facts.supportedSellingPoints.slice(0, 2);
  const bases = [`${facts.skuName}的${points[0] ?? "产品细节"}`, `${facts.skuName}在${request.scene || "日常"}里的体验`, `${facts.skuName}的规格与送礼场景`];
  return bases.map((title, index) => { const score = { clickPotential: 78 + index * 3, relevance: 90 - index * 3, emotion: 72 + index * 4, information: 84 - index * 2, differentiation: 76 + index * 4, brandFit: 89 - index, commercialValue: 82 + index * 2, total: 0 }; score.total = Math.round((score.clickPotential + score.relevance + score.emotion + score.information + score.differentiation + score.brandFit + score.commercialValue) / 7); return { title, rationale: `围绕已验证的${points.join("、") || "商品信息"}，兼顾${request.audience || "目标受众"}的阅读场景。`, score }; }).sort((a, b) => b.score.total - a.score.total);
}

function scenes(facts: EcommerceProductFacts, rule: typeof styleRules[StylePreset], request: EcommerceAgentRequest): VideoScene[] {
  const total = Number(request.duration ?? "30"); const count = total <= 15 ? 3 : total <= 30 ? 4 : total <= 60 ? 5 : 6; const seconds = `${Math.max(2, Math.floor(total / count))}s`;
  return Array.from({ length: count }, (_, i) => ({ sceneNumber: i + 1, duration: seconds, voiceover: i === 0 ? `${rule.hook}：${facts.skuName}，先看这一个细节。` : i === count - 1 ? `${rule.cta}。` : `围绕${facts.supportedSellingPoints[i % facts.supportedSellingPoints.length] || "已验证商品特点"}展开。`, visual: i === 0 ? rule.visual : i === count - 1 ? "产品与收束画面" : "产品局部与使用场景", shotType: i === 0 ? "特写" : i % 2 ? "中景" : "近景", action: i === 0 ? "拿起产品并进入画面" : "展示产品细节", subtitle: i === 0 ? clip(rule.hook, 16) : clip(facts.supportedSellingPoints[i % facts.supportedSellingPoints.length] || facts.skuName, 16), transition: rule.pacing === "快" || rule.pacing === "中快" ? "快速切镜" : "自然叠化", audio: rule.pacing === "快" ? "轻快节拍" : "低频环境音乐" }));
}

export function buildContentPackage(facts: EcommerceProductFacts, request: EcommerceAgentRequest, generatedCopy: string): ContentPackage {
  const platform = request.platform ?? "xiaohongshu"; const goal = request.goal ?? "seeding"; const style = presetFrom(request); const rule = styleRules[style]; const points = request.sellingPoints?.filter((point) => facts.supportedSellingPoints.includes(point) || ["规格", "包装", "送礼", "场景"].includes(point)).slice(0, 3) ?? facts.supportedSellingPoints.slice(0, 2); const angles = makeAngles(facts, request); const dna = request.referenceText ? [`句子偏${request.referenceText.length < 180 ? "短" : "中长"}`, request.referenceText.includes("！") ? "情绪强度偏高" : "克制标点", "参考表达已转为可执行约束"] : ["未提供参考表达，使用 Style Preset 与品牌克制语气"]; const brandNotes = ["避免无依据的产区、销量、功效与促销承诺", ...rule.avoid.map((item) => `避免：${item}`), ...(style === "custom" && request.customStyle ? [`自定义约束：${clip(request.customStyle, 70)}`] : [])];
  const titleBase = `${facts.skuName}｜${points[0] || "产品细节"}`;
  return { strategy: { platform, goal, audience: request.audience || "AI 推荐", sellingPoints: points, style, styleProfile: dna }, angles, selectedAngle: angles[0], titles: ["稳妥型", "点击型", "搜索型", "情绪型", "转化型"].map((type, i) => ({ type, text: i === 0 ? `${titleBase}，适合什么场景？` : i === 1 ? `别急着选茶，先看${facts.skuName}这个细节` : i === 2 ? `${facts.skuName}${facts.netContent}规格与口感说明` : i === 3 ? `留给自己的一段安静时间，从${facts.skuName}开始` : `${facts.skuName}：把${points[0] || "产品细节"}讲清楚` })), hooks: [{ type: "利益 Hook", text: `${facts.skuName}，把${points[0] || "产品细节"}讲清楚再决定。` }, { type: "好奇 Hook", text: `为什么同样是选茶，这个细节值得先看？` }, { type: "场景 / 情绪 Hook", text: `${request.scene || "午后"}想慢下来时，我会先看这一杯。` }], copy: generatedCopy, videoScript: { duration: `${request.duration ?? (platform === "douyin" ? "30" : "30")} 秒`, scenes: scenes(facts, rule, request) }, visualPlan: [rule.visual, `场景：${request.scene || "干净桌面或自然光窗口"}`, `画面重点：${points.join("、") || "产品细节"}`, `字幕：${rule.subtitle}`, "补拍：开箱、产品特写、手部动作与环境空镜"], coverIdeas: [1, 2, 3].map((n) => ({ title: n === 1 ? `${facts.skuName}，先看这个细节` : n === 2 ? `${facts.skuName}的${points[0] || "产品体验"}` : "一份克制的选茶建议", subject: "产品与使用场景", composition: rule.visual, hierarchy: "大标题→产品主体→小字事实" })), socialCards: ["封面", "场景 / 痛点", "核心内容", "产品事实", "CTA"].map((role, i) => ({ page: i + 1, role, headline: i === 0 ? `${facts.skuName}的一个细节` : role, content: i === 3 ? `${facts.specification}｜${facts.netContent}｜${facts.packaging}` : i === 4 ? rule.cta : `围绕${angles[0].title}展开` })), ctas: [{ type: "软 CTA", text: "把适合自己的那一条信息留住。" }, { type: "互动 CTA", text: "你更在意口感、场景还是包装？" }, { type: "转化 CTA", text: "确认商品信息后，再选择适合你的规格。" }], brandVoice: { passed: true, notes: brandNotes }, decisionSummary: [`当前平台为${platformLabel[platform]}，因此采用${rule.pacing}节奏与${rule.cta}。`, `目标为${goalLabel[goal]}，优先推荐“${angles[0].title}”。`, `已使用${style} Style Router；${dna.join("；")}。`, `商品事实仅来自已验证 SKU；未提供项保持待补充。`] };
}
