"use client";

import { useState } from "react";
import { AlertTriangle, CheckCircle2, ChevronDown, CircleAlert, Database, Download, FileSearch, FileText, LoaderCircle, Search, ShieldCheck, Sparkles, Upload, Workflow } from "lucide-react";
import type { MatchStatus, TenderAgentResult, TenderAgentRequest, TenderSource } from "@/types/tender-agent";

const statusStyle: Record<MatchStatus, string> = { PASS: "bg-emerald-100 text-emerald-800", PARTIAL: "bg-amber-100 text-amber-900", MISSING: "bg-red-100 text-red-800", UNKNOWN: "bg-neutral-200 text-neutral-700" };
const statusLabel: Record<MatchStatus, string> = { PASS: "符合", PARTIAL: "部分符合", MISSING: "缺失", UNKNOWN: "资料不足" };
const riskStyle = { HIGH: "bg-red-100 text-red-800", MEDIUM: "bg-amber-100 text-amber-900", LOW: "bg-emerald-100 text-emerald-800" };

function SourceChips({ sources }: { sources: TenderSource[] }) { return <div className="mt-3 flex flex-wrap gap-1.5">{sources.length ? sources.map((source) => <span title={source.excerpt} key={`${source.id}-${source.location}`} className="rounded-full border border-black/10 bg-white px-2 py-1 text-[10px] text-neutral-500">来源：{source.title} · {source.location}</span>) : <span className="text-[11px] text-neutral-400">暂无可核验证据</span>}</div>; }

export function TenderAgentWorkspace() {
  const [result, setResult] = useState<TenderAgentResult>(); const [error, setError] = useState(""); const [running, setRunning] = useState(false); const [file, setFile] = useState<File>(); const [reviewed, setReviewed] = useState(false);
  async function run(input: TenderAgentRequest) { if (running) return; setRunning(true); setError(""); setReviewed(false); try { const response = await fetch("/api/tender-agent", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); const data = await response.json() as TenderAgentResult & { message?: string }; if (!response.ok) throw new Error(data.message || "分析未完成。"); setResult(data); } catch (err) { setError(err instanceof Error ? err.message : "分析未完成。"); } finally { setRunning(false); } }
  async function upload() { if (!file) { setError("请先选择文件，或直接运行示例招标文件。"); return; } if (!/\.(txt|md)$/i.test(file.name)) { setError("当前真实解析支持 TXT / Markdown；PDF、Word 已预留 OCR 接口但尚未接入解析服务，请先导出为文本，或使用示例文件。 "); return; } await run({ mode: "upload", fileName: file.name, content: await file.text() }); }
  function exportResult() { if (!result) return; const text = `# 招投标分析建议\n\n## 项目\n${result.document.projectInfo.projectName}\n\n## 匹配度\n${result.matchScore.value}%\n${result.matchScore.formula}\n\n## 偏离分析\n${result.matches.map((item) => `- [${statusLabel[item.status]}] ${item.requirement}\n  - 我方能力：${item.ourCapability}\n  - 建议：${item.suggestedAction}`).join("\n")}\n\n## 人工确认\n${result.notice}`; const url = URL.createObjectURL(new Blob([text], { type: "text/markdown;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = "招投标分析建议.md"; link.click(); URL.revokeObjectURL(url); }
  return <section className="bg-[#f7f8f9] py-14 lg:py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8">
    <div className="max-w-4xl"><p className="section-kicker">AI Tender & Solution Agent · Phase 5</p><h1 className="mt-4 text-4xl font-medium tracking-[-0.05em] sm:text-6xl">AI 招投标与方案生成 Agent</h1><p className="mt-5 max-w-3xl text-sm leading-7 text-neutral-500">从招标文件出发，Agent 规划并调用企业资质、产品能力与案例检索工具，输出可追溯的需求拆解、资格检查、偏离分析和技术响应建议。这里展示的是 POC 工作流，所有企业资料均为 Synthetic Demo Data。</p></div>
    <div className="mt-10 grid gap-5 xl:grid-cols-[330px_minmax(0,1fr)]">
      <aside className="rounded-[28px] border border-black/5 bg-white p-5 shadow-soft sm:p-6"><div className="flex items-center gap-2"><FileSearch size={16} /><h2 className="font-medium">招标材料输入</h2></div><p className="mt-3 text-xs leading-6 text-neutral-500">使用示例文件可完整体验闭环；上传文本会在服务端解析。文件内容仅作待分析资料，不会被当成系统指令。</p><button onClick={() => run({ mode: "sample" })} disabled={running} className="mt-5 flex w-full items-center justify-center gap-2 rounded-full bg-[#c7ff4d] px-4 py-3 text-sm font-medium disabled:opacity-60"><Sparkles size={16} />运行 Sample 招标文件</button><div className="my-5 flex items-center gap-3 text-[11px] text-neutral-400"><span className="h-px flex-1 bg-black/10" />或上传材料<span className="h-px flex-1 bg-black/10" /></div><label className="block cursor-pointer rounded-2xl border border-dashed border-black/15 bg-[#f7f8f9] p-4 text-center text-xs text-neutral-500"><Upload className="mx-auto mb-2" size={18} /><span className="block font-medium text-neutral-700">{file ? file.name : "选择 TXT / Markdown"}</span><span className="mt-1 block">PDF / Word 已预留 OCR 接口</span><input className="sr-only" type="file" accept=".txt,.md,.pdf,.doc,.docx,text/plain,text/markdown" onChange={(event) => setFile(event.target.files?.[0])} /></label><button onClick={upload} disabled={running || !file} className="mt-3 flex w-full items-center justify-center gap-2 rounded-full border border-black/10 px-4 py-3 text-sm font-medium disabled:opacity-40"><Upload size={15} />解析上传文件</button><div className="mt-6 rounded-2xl bg-black p-4 text-xs leading-6 text-white/65"><p className="font-medium text-white">当前边界</p><p className="mt-1">TXT / Markdown：真实解析。PDF / Word / 扫描件：OCR Tool Interface 已展示，当前未配置解析服务，使用 Sample fallback 验证流程。</p></div></aside>
      <div className="space-y-5"><section className="rounded-[28px] border border-black/5 bg-white p-5 shadow-soft sm:p-6"><div className="flex items-start justify-between gap-5"><div><p className="text-sm font-medium">Agent 执行过程</p><p className="mt-1 text-xs text-neutral-500">仅展示工具输入、结果、来源与状态；不展示内部推理过程。</p></div>{result && <span className="rounded-full bg-[#edf7d5] px-3 py-1.5 text-xs font-medium">{result.planner.mode === "deepseek-structured" ? "DeepSeek Structured Planner" : "Rule Planner Fallback"}</span>}</div><div className="mt-6 grid gap-3 md:grid-cols-2">{(result?.execution ?? ["解析招标文件", "提取结构化需求", "检索企业资料", "逐条要求匹配", "生成技术响应建议"]).map((item, index) => typeof item === "string" ? <div key={item} className="rounded-2xl border border-dashed border-black/10 p-4 text-neutral-400"><span className="text-[11px] font-medium">{String(index + 1).padStart(2, "0")}</span><p className="mt-3 text-sm">{item}</p></div> : <details key={item.id} className="group rounded-2xl border border-black/10 bg-[#f7f8f9] p-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><div><span className="text-[11px] font-medium text-neutral-400">{String(index + 1).padStart(2, "0")}</span><p className="mt-1 text-sm font-medium">{item.label}</p></div><ChevronDown className="transition group-open:rotate-180" size={16} /></summary><p className="mt-3 text-xs leading-6 text-neutral-600">{item.resultSummary}</p><div className="mt-3 grid gap-2 text-[11px] text-neutral-500"><p>作用：{item.purpose}</p><p>输入：{item.inputSummary}</p><p>状态：{item.status === "not_configured" ? "未配置" : "完成"} · {item.durationMs} ms</p></div><SourceChips sources={item.sources} /></details>)}</div>{running && <p className="mt-5 flex items-center gap-2 rounded-xl bg-[#f7f8f9] px-4 py-3 text-sm text-neutral-600"><LoaderCircle className="animate-spin" size={16} />正在由 Planner 选择并执行所需工具…</p>}</section>
      {error && <div role="alert" className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900"><AlertTriangle className="mt-0.5 shrink-0" size={18} />{error}</div>}
      {result ? <ResultView result={result} reviewed={reviewed} onReview={() => setReviewed(true)} onExport={exportResult} /> : <section className="flex min-h-[350px] flex-col items-center justify-center rounded-[28px] border border-dashed border-black/10 bg-white p-8 text-center"><Workflow size={34} className="text-neutral-300" /><h2 className="mt-4 text-lg font-medium">等待一份待分析的招标文件</h2><p className="mt-2 max-w-md text-sm leading-6 text-neutral-500">运行示例后，这里将展开需求结构、资格匹配、偏离表、风险与带来源的技术响应建议。</p></section>}</div>
    </div>
    <PortfolioNarrative />
  </div></section>;
}

function ResultView({ result, reviewed, onReview, onExport }: { result: TenderAgentResult; reviewed: boolean; onReview: () => void; onExport: () => void }) { return <div className="space-y-5"><section className="rounded-[28px] border border-black/5 bg-white p-5 shadow-soft sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-medium">项目基本信息</p><h2 className="mt-2 text-2xl font-medium tracking-[-0.04em]">{result.document.projectInfo.projectName}</h2><p className="mt-2 text-sm text-neutral-500">{result.document.name}</p></div><div className="rounded-2xl bg-[#edf7d5] px-4 py-3 text-center"><p className="text-[11px] text-neutral-500">总体匹配度</p><p className="mt-1 text-2xl font-medium">{result.matchScore.value}%</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["预算", result.document.projectInfo.budget], ["截止时间", result.document.projectInfo.deadline], ["交付周期", result.document.projectInfo.deliveryPeriod], ["地点", result.document.projectInfo.location]].map(([label, value]) => <div key={label} className="rounded-2xl bg-[#f7f8f9] p-3"><p className="text-[11px] text-neutral-400">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div>)}</div>{result.document.scoringRules.length > 0 && <div className="mt-4 rounded-2xl bg-[#f7f8f9] p-4"><p className="text-xs font-medium">评分标准</p><div className="mt-2 space-y-1">{result.document.scoringRules.map((item) => <p className="text-xs leading-6 text-neutral-600" key={item.description}>{item.description} <span className="text-neutral-400">· {item.source.location}</span></p>)}</div></div>}<p className="mt-4 text-xs leading-6 text-neutral-500">{result.matchScore.formula}</p></section>
  <section className="rounded-[28px] border border-black/5 bg-white p-5 shadow-soft sm:p-6"><p className="text-sm font-medium">招标要求偏离分析</p><p className="mt-1 text-xs text-neutral-500">按确定性匹配规则计算：符合 {result.matchScore.passed} 项 · 部分符合 {result.matchScore.partial} 项 · 缺失 {result.matchScore.missing} 项 · 资料不足 {result.matchScore.unknown} 项。</p><div className="mt-5 overflow-x-auto"><table className="min-w-[820px] w-full text-left text-xs"><thead className="border-b border-black/10 text-neutral-400"><tr><th className="pb-3 pr-4 font-medium">招标要求</th><th className="pb-3 pr-4 font-medium">我方能力</th><th className="pb-3 pr-4 font-medium">匹配状态</th><th className="pb-3 pr-4 font-medium">风险</th><th className="pb-3 font-medium">建议动作</th></tr></thead><tbody>{result.matches.map((match) => <tr key={match.requirementId} className="border-b border-black/5 align-top"><td className="py-4 pr-4 leading-6 font-medium">{match.requirement}<SourceChips sources={match.evidence} /></td><td className="py-4 pr-4 leading-6 text-neutral-600">{match.ourCapability}</td><td className="py-4 pr-4"><span className={`rounded-full px-2 py-1 ${statusStyle[match.status]}`}>{statusLabel[match.status]}</span></td><td className="py-4 pr-4"><span className={`rounded-full px-2 py-1 ${riskStyle[match.risk]}`}>{match.risk}</span></td><td className="py-4 leading-6 text-neutral-600">{match.suggestedAction}</td></tr>)}</tbody></table></div></section>
  <section className="grid gap-5 lg:grid-cols-[0.82fr_1.18fr]"><div className="rounded-[28px] border border-black/5 bg-white p-5 shadow-soft sm:p-6"><div className="flex items-center gap-2"><CircleAlert size={16} /><p className="text-sm font-medium">关键风险与人工确认</p></div><div className="mt-5 space-y-3">{result.risks.length ? result.risks.map((risk) => <div key={risk.relatedRequirementIds[0]} className="rounded-2xl bg-[#f7f8f9] p-4"><span className={`rounded-full px-2 py-1 text-[10px] font-medium ${riskStyle[risk.level]}`}>{risk.level}</span><p className="mt-3 text-sm font-medium">{risk.title}</p><p className="mt-2 text-xs leading-6 text-neutral-600">{risk.description}</p></div>) : <p className="text-sm text-neutral-500">未发现需要升级的风险项；仍需人工复核。</p>}</div><button onClick={onReview} className="mt-5 flex w-full items-center justify-center gap-2 rounded-full bg-black px-4 py-3 text-sm font-medium text-white"><ShieldCheck size={15} />{reviewed ? "已标记：等待人工复核" : "标记为待人工复核"}</button><button onClick={onExport} className="mt-3 flex w-full items-center justify-center gap-2 rounded-full border border-black/10 px-4 py-3 text-sm font-medium"><Download size={15} />导出分析建议</button></div><div className="rounded-[28px] border border-black/5 bg-white p-5 shadow-soft sm:p-6"><div className="flex items-center gap-2"><FileText size={16} /><p className="text-sm font-medium">技术响应建议</p></div><p className="mt-2 text-xs leading-6 text-neutral-500">仅生成目录与章节建议，不自动生成或提交正式标书。</p><div className="mt-4 flex flex-wrap gap-2">{result.solution.outline.map((item, index) => <span key={item} className="rounded-full border border-black/10 px-2.5 py-1 text-[11px] text-neutral-600">{index + 1}. {item}</span>)}</div><div className="mt-5 space-y-3">{result.solution.sections.map((section) => <details key={section.title} className="group rounded-2xl bg-[#f7f8f9] p-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><p className="text-sm font-medium">{section.title}</p><ChevronDown className="transition group-open:rotate-180" size={16} /></summary><p className="mt-3 text-xs leading-6 text-neutral-600">招标要求：{section.tenderRequirement}</p><p className="mt-2 text-xs leading-6 text-neutral-700">{section.responseSuggestion}</p><p className="mt-2 text-xs leading-6 text-neutral-500">待确认：{section.pendingConfirmation.join("；")}</p><SourceChips sources={section.sources} /></details>)}</div></div></section>
  <section className="rounded-[24px] border border-amber-200 bg-amber-50 p-5 text-sm leading-7 text-amber-950"><div className="flex gap-3"><Database className="mt-1 shrink-0" size={17} /><p>{result.notice}</p></div>{result.toolResults.some((item) => item.status === "not_configured") && <div className="mt-3 flex gap-2 text-xs text-amber-900"><Search size={15} />Web Search：未配置。外部政策与标准可在后续通过 provider adapter 接入；不会用于判断企业内部资质。</div>}</section></div>; }

function PortfolioNarrative() { const cards = [["业务问题", "招标文件信息密集且分散，售前需要在资格、技术、案例和交付之间建立可核验的判断。"], ["需求拆解", "将文本分为项目、资格、技术、评分、时间与交付，并保留原文位置。"], ["解决方案", "让 Planner 选择内部检索工具；让规则引擎处理硬条件、状态与风险。"], ["Tool Calling", "工具结果统一返回 query、results、sources、confidence 与 status，可展开查看。"], ["POC 测试", "覆盖正常文本、硬性条件、冲突、未知能力、注入、服务失败、空文件与 OCR 文本转写。"], ["项目边界", "没有真实客户、真实中标或真实 OCR / Web Search；所有企业资料均为演示数据。"]] as const; return <section className="mt-16"><div className="max-w-3xl"><p className="section-kicker">项目说明与复盘</p><h2 className="mt-4 text-3xl font-medium tracking-[-0.045em] sm:text-4xl">从业务问题到可审计的 Agent 闭环</h2></div><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{cards.map(([title, text], index) => <article key={title} className="rounded-[24px] border border-black/5 bg-white p-5"><p className="text-[11px] font-semibold text-neutral-400">0{index + 1}</p><h3 className="mt-8 text-lg font-medium">{title}</h3><p className="mt-3 text-sm leading-7 text-neutral-500">{text}</p></article>)}</div><div className="mt-5 rounded-[24px] bg-black p-6 text-white"><p className="text-xs font-semibold tracking-[0.14em] text-white/50">复盘</p><p className="mt-3 max-w-4xl text-sm leading-7 text-white/70">这个 POC 的重点不是“让 LLM 自动做投标决策”，而是把不可信招标文本、内部证据、规则判断、风险暴露与人工确认组织成可以现场讲清楚的售前工作流。下一步应补齐真实 OCR、可配置 Web Search、文件解析与正式证据管理。</p></div></section>; }
