import { randomUUID } from "node:crypto";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { embeddingProviderStatus, embedTexts } from "@/lib/tender-agent/embedding-provider";
import { parseBidDocument } from "@/lib/tender-agent/file-parser";
import { ocrDocument } from "@/lib/tender-agent/ocr";
import type { CompanyDocument, CompanyDocumentCategory, CompanyEvidenceChunk } from "@/types/tender-agent";

const root = path.join(process.cwd(), "storage", "tender-company"); const documentsPath = path.join(root, "documents.json"); const chunksPath = path.join(root, "chunks.json"); const filesPath = path.join(root, "files"); const textsPath = path.join(root, "texts");
const imageTypes = new Set(["PNG", "JPG", "JPEG"]); const typeOf = (name: string): CompanyDocument["fileType"] | undefined => ({ ".pdf": "PDF", ".docx": "DOCX", ".txt": "TXT", ".md": "MARKDOWN", ".png": "PNG", ".jpg": "JPG", ".jpeg": "JPEG" })[path.extname(name).toLowerCase()] as CompanyDocument["fileType"] | undefined;
async function ensure() { await Promise.all([mkdir(filesPath, { recursive: true }), mkdir(textsPath, { recursive: true })]); }
async function readJson<T>(file: string, fallback: T): Promise<T> { try { return JSON.parse(await readFile(file, "utf8")) as T; } catch { return fallback; } }
async function writeJson(file: string, value: unknown) { await writeFile(file, JSON.stringify(value, null, 2), "utf8"); }
export async function listCompanyDocuments() { await ensure(); return readJson<CompanyDocument[]>(documentsPath, []); }
export async function listCompanyChunks() { await ensure(); return readJson<CompanyEvidenceChunk[]>(chunksPath, []); }
export async function workspaceStats() { const documents = await listCompanyDocuments(); return { documents: documents.length, parsed: documents.filter((item) => item.parseStatus === "PARSED").length, ocr: documents.filter((item) => item.parseMethod === "ocr").length, indexed: documents.filter((item) => item.indexed).length, failed: documents.filter((item) => item.parseStatus !== "PARSED").length, embedding: embeddingProviderStatus() }; }
function semanticChunks(documentId: string, category: CompanyDocumentCategory, text: string, metadata: CompanyEvidenceChunk["metadata"], pages?: Array<{ pageNumber: number; text: string }>) {
  const chunks: CompanyEvidenceChunk[] = []; const pageGroups = pages?.length ? pages : [{ pageNumber: undefined, text }];
  for (const pageGroup of pageGroups) { let title = "正文"; let buffer: string[] = [];
  const flush = () => { const content = buffer.join("\n").trim(); if (content) chunks.push({ chunkId: `${documentId}-C${String(chunks.length + 1).padStart(3, "0")}`, documentId, content, quote: content, sourceFile: metadata.fileName, category, sectionTitle: title, page: pageGroup.pageNumber, pageNumber: pageGroup.pageNumber, metadata }); buffer = []; };
  for (const paragraph of pageGroup.text.split(/\n\s*\n|\n(?=#|第[一二三四五六七八九十\d]+[章节]|[一二三四五六七八九十]+、|\d+(?:\.\d+)*\s)/)) { const value = paragraph.trim(); if (!value) continue; if (/^(#|第[一二三四五六七八九十\d]+[章节]|[一二三四五六七八九十]+、|\d+(?:\.\d+)*\s)/.test(value) && value.length < 100) { flush(); title = value.replace(/^#+\s*/, ""); continue; } if (buffer.join("\n").length + value.length > 1400) flush(); buffer.push(value); }
  flush();
  }
  return chunks;
}
async function parseAndIndex(file: File, category: CompanyDocumentCategory, fields: Pick<CompanyDocument, "validFrom" | "validTo" | "issuer" | "tags">, existing?: CompanyDocument): Promise<CompanyDocument> {
  await ensure(); const fileType = typeOf(file.name); if (!fileType) throw new Error("unsupported_company_file_type"); const documentId = existing?.documentId ?? `CDOC-${randomUUID()}`; const extension = path.extname(file.name).toLowerCase(); const storedName = `${documentId}${extension}`; const filePath = path.join(filesPath, storedName); const buffer = Buffer.from(await file.arrayBuffer()); if (!existing) await writeFile(filePath, buffer);
  let text = ""; let pageTexts: Array<{ pageNumber: number; text: string }> | undefined; let parseStatus: CompanyDocument["parseStatus"] = "PARSED"; let parseMethod: CompanyDocument["parseMethod"] = "none"; let pageCount: number | undefined; const warnings: string[] = [];
  try { if (imageTypes.has(fileType)) { const ocr = await ocrDocument(buffer, file.type || "application/octet-stream"); text = ocr.text; pageTexts = ocr.pageResults.map((page) => ({ pageNumber: page.page, text: page.text })); parseStatus = ocr.status === "OCR_SUCCEEDED" ? "PARSED" : ocr.status === "OCR_UNAVAILABLE" ? "OCR_UNAVAILABLE" : "OCR_FAILED"; parseMethod = ocr.status === "OCR_SUCCEEDED" ? "ocr" : "none"; pageCount = ocr.pageResults.length || undefined; warnings.push(...ocr.warnings); } else { const parsed = await parseBidDocument(file); text = parsed.text; pageTexts = parsed.pages; pageCount = parsed.pageCount; parseMethod = parsed.parseMethod; if (parsed.status === "OCR_REQUIRED") { const ocr = await ocrDocument(buffer, file.type || "application/pdf"); text = ocr.text; pageTexts = ocr.pageResults.map((page) => ({ pageNumber: page.page, text: page.text })); parseStatus = ocr.status === "OCR_SUCCEEDED" ? "PARSED" : ocr.status === "OCR_UNAVAILABLE" ? "OCR_UNAVAILABLE" : "OCR_FAILED"; parseMethod = ocr.status === "OCR_SUCCEEDED" ? "ocr" : "pdf_text"; warnings.push(parsed.warning ?? "", ...ocr.warnings); } else warnings.push(parsed.warning ?? ""); } } catch (error) { parseStatus = "FAILED"; warnings.push(error instanceof Error ? error.message : "parse_failed"); }
  const document: CompanyDocument = { documentId, fileName: file.name, fileType, category, uploadTime: existing?.uploadTime ?? new Date().toISOString(), parseStatus, parseMethod, textLength: text.length, pageCount, synthetic: false, sourceType: "USER_UPLOAD", validFrom: fields.validFrom, validTo: fields.validTo, issuer: fields.issuer, tags: fields.tags, filePath: storedName, textPath: text ? `${documentId}.txt` : undefined, chunkCount: 0, indexed: false, indexMethod: "KEYWORD", warnings: warnings.filter(Boolean) };
  const documents = (await listCompanyDocuments()).filter((item) => item.documentId !== documentId); const allChunks = (await listCompanyChunks()).filter((item) => item.documentId !== documentId); if (text && parseStatus === "PARSED") { await writeFile(path.join(textsPath, `${documentId}.txt`), text, "utf8"); const chunks = semanticChunks(documentId, category, text, { fileName: document.fileName, validFrom: document.validFrom, validTo: document.validTo, issuer: document.issuer, tags: document.tags, parseMethod: document.parseMethod }, pageTexts); const provider = embeddingProviderStatus(); if (provider.enabled) { try { const vectors = await embedTexts(chunks.map((item) => item.content)); chunks.forEach((item, index) => { item.embedding = vectors[index]; }); document.indexed = true; document.indexMethod = "HYBRID"; } catch { document.indexed = true; document.indexMethod = "KEYWORD"; document.warnings.push("语义索引建立失败，当前已降级为关键词检索。"); } } else { document.indexed = true; document.indexMethod = "KEYWORD"; document.warnings.push("语义检索暂未启用，当前使用关键词检索。"); } document.chunkCount = chunks.length; allChunks.push(...chunks); }
  documents.push(document); await Promise.all([writeJson(documentsPath, documents), writeJson(chunksPath, allChunks)]); return document;
}
export async function ingestCompanyDocument(file: File, category: CompanyDocumentCategory, fields: Pick<CompanyDocument, "validFrom" | "validTo" | "issuer" | "tags">) { return parseAndIndex(file, category, fields); }
export async function getCompanyDocument(documentId: string) { return (await listCompanyDocuments()).find((item) => item.documentId === documentId); }
export async function getCompanyDocumentText(documentId: string) { const document = await getCompanyDocument(documentId); if (!document?.textPath) return ""; try { return await readFile(path.join(textsPath, document.textPath), "utf8"); } catch { return ""; } }
export async function reparseCompanyDocument(documentId: string) { const existing = await getCompanyDocument(documentId); if (!existing) throw new Error("company_document_not_found"); const buffer = await readFile(path.join(filesPath, existing.filePath)); const file = new File([buffer], existing.fileName, { type: "application/octet-stream" }); return parseAndIndex(file, existing.category, { validFrom: existing.validFrom, validTo: existing.validTo, issuer: existing.issuer, tags: existing.tags }, existing); }
export async function deleteCompanyDocument(documentId: string) { const document = await getCompanyDocument(documentId); if (!document) return; const documents = (await listCompanyDocuments()).filter((item) => item.documentId !== documentId); const chunks = (await listCompanyChunks()).filter((item) => item.documentId !== documentId); await Promise.all([writeJson(documentsPath, documents), writeJson(chunksPath, chunks), unlink(path.join(filesPath, document.filePath)).catch(() => undefined), document.textPath ? unlink(path.join(textsPath, document.textPath)).catch(() => undefined) : Promise.resolve()]); }
