import { randomUUID } from "node:crypto";
import { embeddingProviderStatus, embedTexts } from "@/lib/tender-agent/embedding-provider";
import { parseBidDocument } from "@/lib/tender-agent/file-parser";
import { ocrDocument } from "@/lib/tender-agent/ocr";
import { getCompanyStorageProvider, readCompanyJson, writeCompanyJson } from "@/lib/tender-agent/company-storage";
import type { CompanyDocument, CompanyDocumentCategory, CompanyEvidenceChunk } from "@/types/tender-agent";

const documentsKey = "documents.json"; const chunksKey = "chunks.json";
const fileKey = (name: string) => `files/${name}`; const textKey = (name: string) => `texts/${name}`;
const imageTypes = new Set(["PNG", "JPG", "JPEG"]);
const typeOf = (name: string): CompanyDocument["fileType"] | undefined => ({ ".pdf": "PDF", ".docx": "DOCX", ".txt": "TXT", ".md": "MARKDOWN", ".png": "PNG", ".jpg": "JPG", ".jpeg": "JPEG" })[name.slice(name.lastIndexOf(".")).toLowerCase()] as CompanyDocument["fileType"] | undefined;
const extensionOf = (name: string) => { const dot = name.lastIndexOf("."); return dot >= 0 ? name.slice(dot).toLowerCase() : ""; };
async function documents() { const provider = getCompanyStorageProvider(); return { provider, value: await readCompanyJson<CompanyDocument[]>(provider, documentsKey, []) }; }
async function chunks() { const provider = getCompanyStorageProvider(); return { provider, value: await readCompanyJson<CompanyEvidenceChunk[]>(provider, chunksKey, []) }; }
async function writeWorkspace(documentsValue: CompanyDocument[], chunksValue: CompanyEvidenceChunk[]) { const provider = getCompanyStorageProvider(); await Promise.all([writeCompanyJson(provider, documentsKey, documentsValue), writeCompanyJson(provider, chunksKey, chunksValue)]); }

export async function listCompanyDocuments() { return (await documents()).value; }
export async function listCompanyChunks() { return (await chunks()).value; }
export async function workspaceStats() { const items = await listCompanyDocuments(); return { documents: items.length, parsed: items.filter((item) => item.parseStatus === "PARSED").length, ocr: items.filter((item) => item.parseMethod === "ocr").length, indexed: items.filter((item) => item.indexed).length, failed: items.filter((item) => item.parseStatus !== "PARSED").length, embedding: embeddingProviderStatus() }; }
function semanticChunks(documentId: string, category: CompanyDocumentCategory, text: string, metadata: CompanyEvidenceChunk["metadata"], pages?: Array<{ pageNumber: number; text: string }>) {
  const chunks: CompanyEvidenceChunk[] = []; const pageGroups = pages?.length ? pages : [{ pageNumber: undefined, text }];
  for (const pageGroup of pageGroups) { let title = "正文"; let buffer: string[] = [];
  const flush = () => { const content = buffer.join("\n").trim(); if (content) chunks.push({ chunkId: `${documentId}-C${String(chunks.length + 1).padStart(3, "0")}`, documentId, content, quote: content, sourceFile: metadata.fileName, category, sectionTitle: title, page: pageGroup.pageNumber, pageNumber: pageGroup.pageNumber, metadata }); buffer = []; };
  for (const paragraph of pageGroup.text.split(/\n\s*\n|\n(?=#|第[一二三四五六七八九十\d]+[章节]|[一二三四五六七八九十]+、|\d+(?:\.\d+)*\s)/)) { const value = paragraph.trim(); if (!value) continue; if (/^(#|第[一二三四五六七八九十\d]+[章节]|[一二三四五六七八九十]+、|\d+(?:\.\d+)*\s)/.test(value) && value.length < 100) { flush(); title = value.replace(/^#+\s*/, ""); continue; } if (buffer.join("\n").length + value.length > 1400) flush(); buffer.push(value); }
  flush();
  }
  return chunks;
}
async function indexChunks(items: CompanyEvidenceChunk[], document: CompanyDocument) {
  const provider = embeddingProviderStatus();
  if (provider.enabled) { try { const vectors = await embedTexts(items.map((item) => item.content)); items.forEach((item, index) => { item.embedding = vectors[index]; }); document.indexed = true; document.indexMethod = "HYBRID"; } catch { document.indexed = true; document.indexMethod = "KEYWORD"; document.warnings.push("语义索引建立失败，当前已降级为关键词检索。"); } }
  else { document.indexed = true; document.indexMethod = "KEYWORD"; document.warnings.push("语义检索暂未启用，当前使用关键词检索。"); }
}
async function parseAndIndex(file: File, category: CompanyDocumentCategory, fields: Pick<CompanyDocument, "validFrom" | "validTo" | "issuer" | "tags" | "notes">, existing?: CompanyDocument): Promise<CompanyDocument> {
  const provider = getCompanyStorageProvider(); const fileType = typeOf(file.name); if (!fileType) throw new Error("unsupported_company_file_type"); const documentId = existing?.documentId ?? `CDOC-${randomUUID()}`; const storedName = `${documentId}${extensionOf(file.name)}`; const buffer = Buffer.from(await file.arrayBuffer()); if (!existing) await provider.write(fileKey(storedName), buffer, file.type || "application/octet-stream");
  let text = ""; let pageTexts: Array<{ pageNumber: number; text: string }> | undefined; let parseStatus: CompanyDocument["parseStatus"] = "PARSED"; let parseMethod: CompanyDocument["parseMethod"] = "none"; let pageCount: number | undefined; const warnings: string[] = [];
  try { if (imageTypes.has(fileType)) { const ocr = await ocrDocument(buffer, file.type || "application/octet-stream"); text = ocr.text; pageTexts = ocr.pageResults.map((page) => ({ pageNumber: page.page, text: page.text })); parseStatus = ocr.status === "OCR_SUCCEEDED" ? "PARSED" : ocr.status === "OCR_UNAVAILABLE" ? "OCR_UNAVAILABLE" : "OCR_FAILED"; parseMethod = ocr.status === "OCR_SUCCEEDED" ? "ocr" : "none"; pageCount = ocr.pageResults.length || undefined; warnings.push(...ocr.warnings); } else { const parsed = await parseBidDocument(file); text = parsed.text; pageTexts = parsed.pages; pageCount = parsed.pageCount; parseMethod = parsed.parseMethod; if (parsed.status === "OCR_REQUIRED") { const ocr = await ocrDocument(buffer, file.type || "application/pdf"); text = ocr.text; pageTexts = ocr.pageResults.map((page) => ({ pageNumber: page.page, text: page.text })); parseStatus = ocr.status === "OCR_SUCCEEDED" ? "PARSED" : ocr.status === "OCR_UNAVAILABLE" ? "OCR_UNAVAILABLE" : "OCR_FAILED"; parseMethod = "ocr"; warnings.push(parsed.warning ?? "", ...ocr.warnings); } else warnings.push(parsed.warning ?? ""); } } catch (error) { parseStatus = "FAILED"; warnings.push(error instanceof Error ? error.message : "parse_failed"); }
  const document: CompanyDocument = { documentId, fileName: file.name, fileType, category, uploadTime: existing?.uploadTime ?? new Date().toISOString(), parseStatus, parseMethod, textLength: text.length, pageCount, synthetic: false, sourceType: "USER_UPLOAD", validFrom: fields.validFrom, validTo: fields.validTo, issuer: fields.issuer, tags: fields.tags, notes: fields.notes, filePath: storedName, textPath: text ? `${documentId}.txt` : undefined, chunkCount: 0, indexed: false, indexMethod: "KEYWORD", warnings: warnings.filter(Boolean) };
  const currentDocuments = (await listCompanyDocuments()).filter((item) => item.documentId !== documentId); const allChunks = (await listCompanyChunks()).filter((item) => item.documentId !== documentId); if (text && parseStatus === "PARSED") { await provider.write(textKey(document.textPath!), text, "text/plain; charset=utf-8"); const nextChunks = semanticChunks(documentId, category, text, { fileName: document.fileName, validFrom: document.validFrom, validTo: document.validTo, issuer: document.issuer, tags: document.tags, notes: document.notes, parseMethod: document.parseMethod }, pageTexts); await indexChunks(nextChunks, document); document.chunkCount = nextChunks.length; allChunks.push(...nextChunks); }
  currentDocuments.push(document); await writeWorkspace(currentDocuments, allChunks); return document;
}
export async function ingestCompanyDocument(file: File, category: CompanyDocumentCategory, fields: Pick<CompanyDocument, "validFrom" | "validTo" | "issuer" | "tags" | "notes">) { return parseAndIndex(file, category, fields); }
export async function getCompanyDocument(documentId: string) { return (await listCompanyDocuments()).find((item) => item.documentId === documentId); }
export async function getCompanyDocumentText(documentId: string) { const document = await getCompanyDocument(documentId); if (!document?.textPath) return ""; return ((await getCompanyStorageProvider().read(textKey(document.textPath))) ?? Buffer.from("")).toString("utf8"); }
export async function reparseCompanyDocument(documentId: string) { const existing = await getCompanyDocument(documentId); if (!existing) throw new Error("company_document_not_found"); const buffer = await getCompanyStorageProvider().read(fileKey(existing.filePath)); if (!buffer) throw new Error("company_document_file_not_found"); const file = new File([Uint8Array.from(buffer)], existing.fileName, { type: "application/octet-stream" }); return parseAndIndex(file, existing.category, { validFrom: existing.validFrom, validTo: existing.validTo, issuer: existing.issuer, tags: existing.tags, notes: existing.notes }, existing); }
export async function updateCompanyDocument(documentId: string, updates: Partial<Pick<CompanyDocument, "fileName" | "category" | "tags" | "notes">> & { text?: string }) {
  const existing = await getCompanyDocument(documentId); if (!existing) throw new Error("company_document_not_found"); const provider = getCompanyStorageProvider(); const text = updates.text ?? await getCompanyDocumentText(documentId); const document: CompanyDocument = { ...existing, fileName: updates.fileName?.trim() || existing.fileName, category: updates.category ?? existing.category, tags: updates.tags ?? existing.tags, notes: updates.notes ?? existing.notes, textLength: text.length, textPath: text ? existing.textPath ?? `${documentId}.txt` : undefined, chunkCount: 0, indexed: false, indexMethod: "KEYWORD", warnings: existing.warnings.filter((warning) => !warning.includes("索引")) }; const currentDocuments = (await listCompanyDocuments()).filter((item) => item.documentId !== documentId); const allChunks = (await listCompanyChunks()).filter((item) => item.documentId !== documentId);
  if (text) { document.parseStatus = "PARSED"; await provider.write(textKey(document.textPath!), text, "text/plain; charset=utf-8"); const nextChunks = semanticChunks(documentId, document.category, text, { fileName: document.fileName, validFrom: document.validFrom, validTo: document.validTo, issuer: document.issuer, tags: document.tags, notes: document.notes, parseMethod: document.parseMethod }); await indexChunks(nextChunks, document); document.chunkCount = nextChunks.length; allChunks.push(...nextChunks); }
  currentDocuments.push(document); await writeWorkspace(currentDocuments, allChunks); return document;
}
export async function deleteCompanyDocument(documentId: string) { const document = await getCompanyDocument(documentId); if (!document) return; const currentDocuments = (await listCompanyDocuments()).filter((item) => item.documentId !== documentId); const allChunks = (await listCompanyChunks()).filter((item) => item.documentId !== documentId); await writeWorkspace(currentDocuments, allChunks); await getCompanyStorageProvider().remove([fileKey(document.filePath), ...(document.textPath ? [textKey(document.textPath)] : [])]); }
