import { embeddingProviderStatus, embedTexts } from "@/lib/tender-agent/embedding-provider";
import { listCompanyChunks } from "@/lib/tender-agent/company-workspace";
import type { CompanyDocumentCategory, RetrievedCompanyEvidence, RetrievalMethod } from "@/types/tender-agent";

const normalize = (value: string) => value.toLowerCase().replace(/[\s，。；、：：“”()（）/]/g, "");
const cosine = (a: number[], b: number[]) => { const dot = a.reduce((sum, value, index) => sum + value * (b[index] ?? 0), 0); const left = Math.sqrt(a.reduce((sum, value) => sum + value * value, 0)); const right = Math.sqrt(b.reduce((sum, value) => sum + value * value, 0)); return left && right ? dot / (left * right) : 0; };
function keywordScore(query: string, content: string, tags: string[]) { const q = normalize(query); const target = normalize(`${content}${tags.join(" ")}`); const tagHits = tags.filter((tag) => q.includes(normalize(tag))).length; const cjk = q.match(/[\u4e00-\u9fa5]{2,6}/g) ?? []; const phraseHits = cjk.filter((term) => target.includes(term)).length; const ascii = q.match(/[a-z0-9]{2,}/g) ?? []; return tagHits * 8 + phraseHits * 2 + ascii.filter((term) => target.includes(term)).length * 4; }
export function validateEvidence(validTo?: string): RetrievedCompanyEvidence["validation"] { if (!validTo) return "UNKNOWN"; if (validTo < new Date().toISOString().slice(0, 10)) return "EXPIRED"; return "VALID"; }
export async function retrieveCompanyEvidence(query: string, options: { categories?: CompanyDocumentCategory[]; topK?: number } = {}) {
  const chunks = (await listCompanyChunks()).filter((item) => !options.categories || options.categories.includes(item.category)); const keywords = chunks.map((chunk) => ({ chunk, score: keywordScore(query, chunk.content, chunk.metadata.tags) })).filter((item) => item.score > 0); const provider = embeddingProviderStatus(); let vectors = new Map<string, number>();
  if (provider.enabled && chunks.some((item) => item.embedding?.length)) { try { const [queryEmbedding] = await embedTexts([query]); for (const chunk of chunks) if (chunk.embedding?.length) vectors.set(chunk.chunkId, cosine(queryEmbedding, chunk.embedding)); } catch { vectors = new Map(); } }
  const vectorEntries = Array.from(vectors.entries()).filter(([, score]) => score > .25); const keywordRank = [...keywords].sort((a, b) => b.score - a.score); const vectorRank = [...vectorEntries].sort((a, b) => b[1] - a[1]); const rrf = new Map<string, number>(); const addRrf = (items: string[]) => items.forEach((id, index) => rrf.set(id, (rrf.get(id) ?? 0) + 1 / (60 + index + 1)));
  addRrf(keywordRank.map((item) => item.chunk.chunkId)); addRrf(vectorRank.map(([id]) => id)); const candidateIds = new Set(rrf.keys()); const ranked = chunks.filter((chunk) => candidateIds.has(chunk.chunkId)).map((chunk) => { const keyword = keywords.find((item) => item.chunk.chunkId === chunk.chunkId)?.score ?? 0; const vector = vectors.get(chunk.chunkId) ?? 0; const retrievalMethod: RetrievalMethod = keyword && vector ? "HYBRID" : vector ? "VECTOR" : "KEYWORD"; const pageNumber = chunk.pageNumber ?? chunk.page; return { evidenceId: chunk.chunkId, documentId: chunk.documentId, chunkId: chunk.chunkId, content: chunk.content, quote: chunk.quote || chunk.content, category: chunk.category, score: Math.round(((rrf.get(chunk.chunkId) ?? 0) * 100 + keyword * .01 + vector * .01) * 100) / 100, retrievalMethod, sourceFile: chunk.sourceFile || chunk.metadata.fileName, page: pageNumber, pageNumber, sectionTitle: chunk.sectionTitle, validFrom: chunk.metadata.validFrom, validTo: chunk.metadata.validTo, validation: validateEvidence(chunk.metadata.validTo) } satisfies RetrievedCompanyEvidence; }).sort((a, b) => b.score - a.score).slice(0, options.topK ?? 8);
  return { results: ranked, semanticEnabled: provider.enabled && Boolean(vectors.size), keywordHits: keywordRank.length, vectorHits: vectorRank.length, finalHits: ranked.length, fallback: provider.enabled ? vectors.size ? undefined : "HYBRID_RAG_DEGRADED：语义检索调用失败，已降级为关键词检索。" : "HYBRID_RAG_DEGRADED：语义检索暂未启用，当前使用关键词检索。" };
}
