import type { ExternalVerification } from "@/types/tender-agent";

// TAVILY_API_KEY is canonical; retain the legacy name only for private deployment migration.
const tavilyKey = () => process.env.TAVILY_API_KEY || process.env.TENDER_WEB_SEARCH_API_KEY;
export const tavilyConfigured = () => Boolean(tavilyKey());
export async function externalSearch(query: string): Promise<ExternalVerification> {
  const key = tavilyKey(); if (!key) return { enabled: false, status: "NOT_CONFIGURED", query, error: "missing_api_key", results: [] };
  try { const response = await fetch("https://api.tavily.com/search", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ api_key: key, query, search_depth: "advanced", max_results: 5, include_answer: false }), signal: AbortSignal.timeout(15000) }); if (!response.ok) throw new Error(`http_${response.status}`); const data = await response.json() as { results?: Array<{ title?: string; url?: string; content?: string; published_date?: string }> }; const results = (data.results ?? []).map((item) => { const url = item.url ?? ""; let domain = ""; try { domain = new URL(url).hostname; } catch { domain = "unknown"; } const official = /\.gov\.cn$|\.edu\.cn$|\.org\.cn$/.test(domain); const confidence: "high" | "medium" | "low" = official ? "high" : domain ? "medium" : "low"; return { title: item.title ?? "未命名来源", url, domain, publishedAt: item.published_date, retrievedAt: new Date().toISOString(), snippet: item.content ?? "", provider: "tavily", confidence }; }).filter((item) => item.url).sort((a, b) => Number(b.confidence === "high") - Number(a.confidence === "high")); return results.length ? { enabled: true, status: "COMPLETED", query, results } : { enabled: true, status: "FAILED", query, error: "no_results", results: [] }; } catch (error) { const message = error instanceof Error ? error.message : "network_error"; return { enabled: true, status: "FAILED", query, error: /timeout/i.test(message) ? "timeout" : message, results: [] }; }
}
